version: "3.9"

services:
  monopoly:
    image: htetlinmaung/monopoly
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://{username}:{password}@localhost:27017/monopoly?authSource=admin
      - KAFKA_BROKERS=localhost:9092
      - JWT_SECRET={secret}
    # volumes:
    #   - ./load:/app/load
